seo: 
  site_name: Luca Garden Design
  title: Amenajări grădini cu plante ornamentale și piatră naturală 
  description: Imaginați-vă propria grădină de vis, iar noi vom face posibilă amenajarea ei cu piatră naturală și cele mai frumoase plante ornamentale! Citiți mai mult.
  keywords: Luca Garden Design, amenajare grădină, servicii de amenajări cu piatră naturală, amenajări cu plante ornamentale, amenajări grădini București și Ilfov, servicii de peisagistică
  social_image: /images/social-image.webp
  author: Develveren
  favicon_image: /icons/favicon.ico
social: 
  instagram_username: https://www.instagram.com/p/CcBR95ENQlo/
  facebook_url: https://www.facebook.com/lucaartgarden/ 
design: 
  dark-text_color: '#14170f'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: '#ffffff'
  light-grey-text_color: '#e3e7db'
  featured-text_color: '#87a84f'
  dark_color: '#14170f'
  orange_color: '#ffebb6'
  light_color: '#E9F6D0'
  v-light_color: '#f9f9f9'
  featured_color: '#87a84f'
  accent_color: 'rgb(167, 74, 74)'
