seo: 
  site_name: Luca Garden Design
  title: Default SEO Title
  description: 
  keywords: 
  social_image: 
  author: 
  favicon_image: 
social: 
  instagram_username:
  facebook_url:
  twitter_username: 
design: 
  dark-text_color: '#14170f'
  medium-text_color: 'rgb(90,90,95)'
  light-text_color: 'white'
  light-grey-text_color: '#e3e7db'
  featured-text_color: '#A5CF61'
  dark_color: '#14170f'
  orange_color: '#ffebb6'
  light_color: '#E9F6D0'
  v-light_color: '#f9f9f9'
  featured_color: '#A5CF61'
  accent_color: 'rgb(167, 74, 74)'
